### ISSUE TITLE
Is v1.0 going to be released anytime soon?

### ISSUE THREAD

**Issue by rayluo** [ChartsCSS/charts.css#48]
Hi Rami, I notice that there was a "1.0.0" commit recently. Another recent commit even mentioned pie chart. Is release 1.0.0 and/or pie chart coming soon? :-)  Can't wait to try it out.

**Comment by ramiy** [comment]
The `master` branch has many new code changes since the release of `v0.0.9`. There are a11y improvements and labels alignments bug fixes. Even a new Pie chart implementation, but it's not ready for production yet. All the circular charts are tricky, they require many custom variables which I'm trying to avoid to simplify the usage.

With JS I could solve many of the obstacles but it's a CSS framework. It takes time to overcome some of the challenges as no one ever developer a pure CSS framework like this before and there is no one to learn from.

There are alternative ways to implement some of the features but they come at the expense of ease-of-use. I prefer a longer dev cycle over sacrificing the ease-of-use.

**Comment by JakesFouche** [comment]
Hey @ramiy.

Do you maybe have an update on this? Really looking forward to that Pie Chart.
